### ISSUE TITLE
[deno]章立てを考える

### ISSUE THREAD

**Issue by k2-kanda** [openstandia/ng-js-runtime-docs#2]

**Comment by kannoixia** [comment]
- セットアップ
  - ゼロコンフィグに関して
- TypeScript
- CLI
- モジュール・パッケージマネージャ
- 標準ライブラリ
- npmモジュールの利用
- 環境変数
- ビルド

Deno固有なもの
- プラグイン
- モジュールシステムの考え方（↑と被るようなら削除）
- セキュリティ
