### ISSUE TITLE
[deno]Get Started

### ISSUE THREAD

**Issue by k2-kanda** [openstandia/ng-js-runtime-docs#5]

**Comment by jumpei-kanno** [comment]
- [公式HP](https://docs.deno.com/runtime/manual/)を参考に環境に合わせたインストールを実行
- `deno -version`でコマンドの使用可否を確認
- 簡単なWebサーバーを作成しdenoでの実行を確認
- プロキシ設定は環境変数`HTTP_PROXY`、`HTTPS_PROXY`及び`NO_PROXY`から読み込まれる
- 証明書は`--cert <path>`オプションでカスタム証明書を使用可能
  - 環境変数に`DENO_TLS_CA_STORE=system`を追加することでシステム上の証明書を使用するように設定可能
  - 菅野の環境では上記いづれかの対応をしないとエラーが発生

**Comment by jumpei-kanno** [comment]
初期構築が完了したためクローズ
